# see https://www.dartlang.org/guides/language/analysis-options#the-analysis-options-file
analyzer:
  strong-mode: true
    implicit-casts: false
    implicit-dynamic: false
#   exclude:
#     - path/to/excluded/files/**

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    - cancel_subscriptions
    - close_sinks
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
