name: browser_detect
version: 1.0.2
author: Dan Schultz <dan@mixbook.com>
description: A library that provides information about the user's web browser.
homepage: http://www.github.com/danschultz/browser_detect.dart
dependencies:

dev_dependencies:
  browser: any
  unittest: any
